config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  devise_for :users

  root to: 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'contact', to: 'welcome#contact'
  post 'contact', to: 'welcome#contact'
  get 'booking', to: 'welcome#booking'
  get 'work', to: 'welcome#work'
  get 'home', to: 'welcome#index'
  get 'confirm', to: 'welcome#confirm'
  post 'confirm', to: 'welcome#confirm'
  # resources :messages, only: [:create, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :subject, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
end

app/controllers/welcome_controller.rb
require 'open-uri'
require 'json'

class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :about, :contact, :work, :booking, :confirm]

  def index
    if request.xhr?

      arrival = params[:arrival].to_date
      departure = params[:departure].to_date

      @url = {
        url: "https://booking.cafehostel.com.br/en/hqb/drjl9zZq6b/availability?arrival=#{arrival.year}-#{arrival.month}-#{arrival.day}&departure=#{departure.year}-#{departure.month}-#{departure.day}"
      }

      respond_to do |format|
        format.json { render json: @url }
        format.html
      end

      # url = "https://booking.cafehostel.com.br/en/hqb/drjl9zZq6b/availability?arrival=#{arrival.year}-#{arrival.month}-#{arrival.day}&departure=#{departure.year}-#{departure.month}-#{departure.day}"
      # raw_url = open(url).read
      # html = Nokogiri::HTML(raw_url)
      #
      # even = html.search(".even")
      # odd = html.search(".odd")
      # @images = [
      #   # 11 beds room
      #   ["https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/33308ee8e5b62a25c8f86bdb3822ac88.jpg",
      #    "https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/8d6fcc652d69180b0fa8af317aa18f65.jpg",
      #    "https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/2b17e62ef7cb281560c15c51b85d2b47.jpg"],
      #   # 9 beds room
      #    ['https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/7ad64e499dc4b607fe16c10f45e9b092.jpg',
      #     'https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/e5fbf80d4d2a964217e61f0f081b5583.jpg'],
      #   # Private room
      #    ['https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/7b22ef0ed94fd70367531a961417dfb4.jpg',
      #     'https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/c5c8eb80b8e6a9851e7347dd89372453.jpg'],
      #   # 6 beds room
      #    ['https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/886ddd858c30cda2afabc0d2acd1c70b.jpg',
      #     'https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/b1c11ea0bfd326549c40e0f3ba752a91.jpg'],
      #   # 4 beds room
      #    ['https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/1e8577dd113310b07d6b3e5554f5f0ae.jpg',
      #     'https://s3-sa-east-1.amazonaws.com/hqbeds.com.br/drjl9zZq6b/7f605e6901ca12d60fa4f394cb7fc189.jpg']
      # ]
      # @names = []
      # @prices = []
      # @units = []
      #
      # even.each do |item|
      #   # @images <<  item.search("img").attribute('src').text
      #   @names << item.search('.col-md-3 h6').text.delete("\n").strip.split("  ")
      #   @prices << item.search(".col-md-5 h6 b").text.delete("\n").strip.split("  ")
      #   if item.search("select").attribute('disabled').nil?
      #     @units << item.search("select").text.delete("\n").strip.split(" ")
      #   else
      #     @units << ["disabled"]
      #   end
      # end
      #
      # odd.each do |item|
      #   # @images <<  item.search("img").attribute('src').text
      #   @names << item.search('.col-md-3 h6').text.delete("\n").strip.split("  ")
      #   @prices << item.search(".col-md-5 h6 b").text.delete("\n").strip.split("  ")
      #   if item.search("select").attribute('disabled').nil?
      #     @units << item.search("select").text.delete("\n").strip.split(" ")
      #   else
      #     @units << ["disabled"]
      #   end
      # end
      #
      # @names.each do |name|
      #   name.map { |n| name.delete(n) if n == "" }
      # end
      #
      # @prices.each do |price|
      #   price.map { |p| price.delete(p) if p == "" }
      # end
      #
      # @result = {
      #   images: @images,
      #   names: @names,
      #   prices: @prices,
      #   units: @units,
      #   arrive: params[:arrival],
      #   departure: params[:departure]
      # }
      #
      # respond_to do |format|
      #   format.json { render json: @result }
      #   format.html
      # end
    end
  end

  def about
    @employees = Employee.all if Employee.all
  end

  def contact
    if request.xhr? && request.method == "POST"
      message = Message.new(
                  name: params['name'],
                  email: params['email'],
                  subject: params['subject'],
                  content: params['message']
                )
      message.save ? status = true : status = false
      @result = {
        status: status
      }

      ApplicationMailer.new_message_from_website(message).deliver_now

      respond_to do |format|
        format.json { render json: @result }
        format.html
      end

    end
  end

  def booking
     redirect_to root_url
  end

  def work
  end

  def confirm
    if request.xhr? && request.method == "POST"
      guest = Guest.new(
                first_name: params['first_name'],
                last_name: params['last_name'],
                email: params['email'],
                phone: params['phone'],
                country: params['country'],
                notes: params['notes'],
                descount_cupom: params['descount_cupom'],
                arrive: params['arrive'],
                departure: params['departure'],
                subtotal_price: params['subtotal_price'],
                breakfast: params['breakfast'],
                breakfast_value: params['breakfast_value'],
                total_price: params['total_price'],
                room: params['room']
              )
      guest.save!
      guest.save ? status = true : status = false
      @result = {
        status: status
      }
      respond_to do |format|
        format.json { render json: @result }
        format.html
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title class="notranslate"> Café Hostel</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'cafehostel.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'partials/sidebar' %>
    <%= render 'partials/navbar' %>
    <%= render 'partials/overlay' %>
    <%= yield %>
    <%= render 'partials/livechat' %>
    <%= render 'partials/footer' %>
    <%= javascript_include_tag 'booking.js' %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-49861311-1"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-49861311-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-49861311-1');
    </script>
    <!-- END: Global site tag (gtag.js) - Google Analytics -->

    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s)
      {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};
      if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
      n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t,s)}(window, document,'script',
      'https://connect.facebook.net/en_US/fbevents.js');
      fbq('init', '1433213603461762');
      fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=1433213603461762&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

    <script>
      $(document).ready(function(){
        if (window.innerWidth < 600) {
          $("#booking").data("need-validation", false);
        } else {
          $("#booking").data("need-validation", true);
        }
        $(window).scroll(function() {
          var searchBar = $("#fixedBookingRow");
          if (searchBar.length > 0) {

            var searchBarHeight = parseInt(searchBar.css("height").replace("px", ""));
            var searchBarPosition = $("#fixedBookingRow").position()['top'];
            var bodyScrollTop = $(this).scrollTop();

            if (bodyScrollTop > searchBarHeight + searchBarPosition) {
              if ($(window).width() < 600) {
                $(".mobileAndWidthSmallHide").hide();
                $("#booking").attr("href", "https://booking.cafehostel.com.br/en/hqb/drjl9zZq6b/availability");
                $("#booking").attr("target", "_blank");
                $("#booking").data("need-validation", false);
              } else {
                $("#booking").removeAttr("href");
                $("#booking").removeAttr("target");
                $(".mobileAndWidthSmallHide").show();
                $("#booking").data("need-validation", true);
              }
              $("#fixedBookingRow").slideDown("fast");
              $("#fixedBookingRow").css("position", "fixed");
              $("#fixedBookingRow").css("top", "0");
              $("#fixedBookingRow").css("right", "0");
              $("#fixedBookingRow").css("left", "0");
              $("#fixedBookingRow").css("margin", "auto");
              $("#fixedBookingRow").css("z-index", "100");
              $("#fixedBookingRow").css("backgroundColor", "rgba(0,0,0,0.9)");
              $(".bookRowInside").css("marginBottom", '0px');
              $(".bookRowInside").css("marginTop", '10px');
              $(".bookRow").css("marginBottom", '0px');
              $(".input-field .material-icons.prefix").css('color', 'white');

            }
            else {
              var display = $(".mobileAndWidthSmallHide").css('display');
              if ($(window).width() < 425) {
                $(".mobileAndWidthSmallHide").show();
              }
              else if ($(window).width() > 425 && display == "none") {
                $(".mobileAndWidthSmallHide").show();
              }
              $("#fixedBookingRow").css("backgroundColor", "transparent");
              $("#fixedBookingRow").css("position", "relative");
              $("#fixedBookingRow").css("margin-bottom", "20vh");
              $(".bookRowInside").css("marginBottom", '20px');
              $(".bookRow").css("marginBottom", '20px');
              $(".input-field .material-icons.prefix").css('color', "rgba(0, 0, 0, 0.87)");
            }
          }
        });
      });
    </script>
  </body>
</html>

app/views/partials/_cards.html.erb
<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ("computador.jpg"), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">watch_later</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate"">Recepção 24hrs</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ("cafe.jpg"), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">local_cafe</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate">Café da manhã caseiro</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ("cozinha.jpg"), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">kitchen</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate">Cozinha</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ("sala.jpg"), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">wifi</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate">Computador grátis</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ('quarto1.jpg'), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">lock</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate">Armários individuais</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ('quarto3.jpg'), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">lightbulb_outline</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate">Luzes para leitura</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ('quarto4.jpg'), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">hotel</i></a>
    </div>
    <div class="card-content activator">
      <p class="truncate">Camas XL</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ('quarto5.jpg'), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">favorite_border</i></a>
    </div>
    <div class="card-content">
      <p class="truncate">Suites</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

<div class="col s12 m4">
  <div class="card">
    <div class="card-image">
      <%= image_tag ('banheiro.jpg'), class: "activator", style: "cursor: pointer;" %>
      <a class="btn-floating halfway-fab waves-effect waves-light amber activator"><i class="material-icons">wc</i></a>
    </div>
    <div class="card-content">
      <p class="truncate">Banheiro próximo aos quartos</p>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
    </div>
  </div>
</div>

app/views/partials/_contact_us.html.erb
<div class="row">
  <div class="container" style="width: 90% !important">
    <h4 style="padding-left: 2%; padding-top: 2%;" class="black-text">Envie-nos uma mensagem</h4>
  </div>
  <div class="col s10 offset-s1 m8 offset-m2">
    <div class="row form-contact">
      <div class="input-field col s12 m6">
        <input id="name" type="text" class="validate" pattern="[a-zA-Z\s]+" minlength="2">
        <label for="name" data-error="Nome inválido">Nome</label>
      </div>
      <div class="input-field col s12 m6">
        <input id="email" type="email" class="validate">
        <label for="email" data-error="E-mail inválido">E-mail</label>
      </div>
      <div class="input-field col s12">
        <textarea id="subject" class="materialize-textarea" minlength="2"></textarea>
        <label for="subject">Assunto</label>
      </div>
      <div class="input-field col s12">
        <textarea id="message" class="materialize-textarea" minlength="2"></textarea>
        <label for="message">Mensagem</label>
      </div>
      <div class="row center-align">
        <a class="waves-effect waves-light btn btn-large center-align amber" id="send-message" style="cursor: pointer;">enviar</a>
      </div>
      <%= render 'partials/message_errors' %>
      <div class="row">
        <div class="col s12">
          <h5 class="center-align" id="success-message" style="display: none;">Sua mensagem foi enviada com sucesso! Entraremos em contato o mais breve possível!</h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_errors_overlay.html.erb
<div class="col s12">
  <ul>
    <li class="center-align black-text error-message error-message-equal-date" style="display: none;"><a style="cursor: pointer;"><i class="material-icons prefix tiny black-text" style='margin-right: 10px;'>cancel</i></a>"Data de chegada" deve ser maior que "Data de partida" </li>
    <li class="center-align black-text error-message error-message-arrival-date" style="display: none;"><a style="cursor: pointer;"><i class="material-icons prefix tiny black-text" style='margin-right: 10px;'>cancel</i></a>"Data de chegada" precisa de um valor válido </li>
    <li class="center-align black-text error-message error-message-departure-date" style="display: none;"><a style="cursor: pointer;"><i class="material-icons prefix tiny black-text" style='margin-right: 10px;'>cancel</i></a>"Data de partida" precisa de um valor válido </li>
    <li class="center-align black-text error-message error-message-less-date" style="display: none;"><a style="cursor: pointer;"><i class="material-icons prefix tiny black-text" style='margin-right: 10px;'>cancel</i></a>"Data de chegada" precisa ser maior que hoje </li>
  </ul>
</div>

app/views/partials/_fixed_book_bar.html.erb
<div id="fixed-top-booking-bar" style="display: none;">
  <div class="row fixed-top-booking-bar-row">
    <form class="col m12" style="width: 100%;">
      <div class="row fixed-top-booking-bar-row-inside">
        <div class="input-field col s12 m4 mobile-and-width-small-hide">
          <i class="material-icons prefix" for="arrival">date_range</i>
          <input id ="arrival" type="text" class="datepicker">
          <label for="arrival">Data de chegada</label>
        </div>
        <div class="input-field col s12 m4 mobile-and-width-small-hide">
          <i class="material-icons prefix" for="arrival">date_range</i>
          <input id="departure" type="text" class="datepicker">
          <label for="departure">Data de partida</label>
        </div>
        <div class="col s12 m3 center-align">
          <a style="cursor: pointer;" id="booking" class="btn btn-large waves-effect waves-light amber modal-trigger">reservar</a>
        </div>
        <%= render 'partials/whatsapp_number' %>
        <%= render 'partials/errors' %>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
      $(window).scroll(function() {
        var searchBar = $("#fixed-top-booking-bar");
        if (searchBar.length > 0) {
          var bodyScrollTop = $(this).scrollTop();

          if (bodyScrollTop > 100) {
            $("#fixed-top-booking-bar").slideDown("fast");
            if ($(window).width() < 600) {
              $(".mobile-and-width-small-hide").hide();
              $("#booking").attr("href", "https://booking.cafehostel.com.br/en/hqb/drjl9zZq6b/availability");
              $("#booking").attr("target", "_blank");
              $("#booking").data("need-validation", false);
            } else {
              $("#booking").removeAttr("href");
              $("#booking").removeAttr("target");
              $(".mobile-and-width-small-hide").show();
              $("#booking").data("need-validation", true);
            }
            $("#fixed-top-booking-bar").css("position", "fixed");
            $("#fixed-top-booking-bar").css("top", "0");
            $("#fixed-top-booking-bar").css("right", "0");
            $("#fixed-top-booking-bar").css("left", "0");
            $("#fixed-top-booking-bar").css("margin", "auto");
            $("#fixed-top-booking-bar").css("z-index", "100");
            $("#fixed-top-booking-bar").css("backgroundColor", "rgba(0,0,0,0.9)");
            $(".fixed-top-booking-bar-row-inside").css("marginBottom", '0px');
            $(".fixed-top-booking-bar-row-inside").css("marginTop", '10px');
            $(".fixed-top-booking-bar-row").css("marginBottom", '0px');
            $(".input-field .material-icons.prefix").css('color', 'white');
          }
          else {
            $("#fixed-top-booking-bar").css("display", 'none');
            var display = $(".mobile-and-width-small-hide").css('display');
            if ($(window).width() < 425) {
              $(".mobile-and-width-small-hide").show();
            }
            else if ($(window).width() > 425 && display == "none") {
              $(".mobile-and-width-small-hide").show();
            }
          }
        }
      });
  });
</script>

app/views/partials/_google_maps_iframe.html.erb
<div class="container-fluid google-maps" style="min-width: 220px !important; width: 100%; margin: 0 auto;">
  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14630.143755314539!2d-46.6905723!3d-23.5491877!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa7dccbb2735dacb6!2sCaf%C3%A9+Hostel!5e0!3m2!1sen!2sbr!4v1506299102832" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/partials/_navbar.html.erb
<div style="display: flex; justify-content: flex-end; margin: 0px !important; float: right !important;">
  <div class="row">
    <% if params['action'] == 'index' %>
    <a class="btn-floating btn-small waves-effect waves-light hide-on-small-only" target="_blank" href="https://www.facebook.com/cafehostelsp">
      <i class="fa fa-facebook" aria-hidden="true"></i>
    </a>
    <a class="btn-floating btn-small waves-effect waves-light hide-on-small-only" target="_blank" href="https://www.instagram.com/cafehostelsp">
      <i class="fa fa-instagram" aria-hidden="true"></i>
    </a>
    <a class="btn-floating btn-small waves-effect waves-light hide-on-small-only" target="_blank" href="https://www.youtube.com/user/cafehostelsp">
      <i class="fa fa-youtube" aria-hidden="true"></i>
    </a>
    <% end %>
    <%= render 'partials/translate_plugin' %>
  </div>
</div>
<div class="mdl-layout__drawer-button valign-wrapper" aria-expand="false" role="button" tabindex="0" style="margin-top: 15px;">
  <a data-activates="slide-out" class="button-collapse waves-effect waves-light menu"><i class="small material-icons">menu</i></a>

  <%= link_to root_path do %>
    <%= image_tag ('logo.png'), class: 'logo' %>
  <% end %>
</div>

app/views/partials/_sidebar.html.erb
<nav class="side-nav" id="slide-out">
  <ul>
    <li id="side-bar-logo">
      <div class="side-bar-div">
        <%= link_to root_path do %>
          <div class="user-view" style="margin-top: 10%; margin-left: 10%; min-height: 20vh;">
            <div class="background">
                <%= image_tag 'logo.png' %>
            </div>
          </div>
        <% end %>
      </div>
    </li>
    <li>
      <%= link_to about_path do %>
        <i class='material-icons prefix tiny notranslate' style='margin-right: 10px'>home</i>Quem somos
      <% end %>
    </li>
    <li>
      <%= link_to contact_path do %>
        <i class="material-icons prefix tiny notranslate" style="margin-right: 10px;">location_on</i>Contato e Localização
      <% end %>
    </li>
    <li>
      <%= link_to work_path do %>
        <i class="material-icons prefix tiny notranslate" style="margin-right: 10px;">work</i>Trabalhe conosco
      <% end %>
    </li>
  </ul>
</nav>

app/views/partials/_welcome_text.html.erb
<div class="container" style="width: 90% !important">
  <h4 style="padding-left: 2%; padding-top: 2%;">Uma casa para viajantes</h4>
  <blockquote>
    Uma casa para viajantes. Foi com esse intuito que Rogério e César, dois amigos que viajaram pelos cinco continentes, resolveram abrir um hostel com um pouquinho do melhor que eles viram mundo afora. O Café Hostel oferece todo o conforto que um viajante precisa, com quartos arejados, uma cozinha para os hóspedes, espaços de convívio aconchegantes que incentivam a troca e um café/bar que reúne viajantes de todo o mundo com moradores de São Paulo. Isto a 2 minutos do metrô, numa rua tranquila da Vila Madalena, bairro boêmio de Sao Paulo.
  </blockquote>
</div>

app/views/welcome/confirm.html.erb
<h1>hello</h1>